name: simple_calendar
description: A simple calendar for personal use.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lunar: ^1.3.3
  intl: ^0.17.0
  provider: ^6.0.0
  fluro: ^2.0.5
  flutter_swiper : ^1.1.6
  dio: ^5.1.2
  flutter_weather_bg: ^2.8.2
  flutter_dotenv: ^5.0.2
  pretty_dio_logger: ^1.3.1
  geolocator: ^9.0.2
  sqflite: ^2.2.8+2
  path: ^1.8.2
  flutter_cupertino_datetime_picker: ^3.0.0
  uuid: ^3.0.7
  logger: ^1.3.0
  flutter_svg: ^2.0.0+1
  weather_icons: ^2.0.2
  flashy_tab_bar2: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - statics/icons/
